name: 'Setup Zig environment'
description: 'Set up a specific version of Zig and add the command-line tools to the PATH.'
author: 'step-security'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  zig-version:
    required: true
    description: 'Exact version of Zig to use.'
  target-platform:
    required: false
    description: 'Platform and arch of Zig to use.'

runs:
  using: 'node20'
  main: 'dist/index.js'
